[window]
decorations = "None"

[window.padding]
x = 8
y = 8

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
